name: Production Build & Push

on:
  push:
    branches:
      - main

env:
  DOCKER_REGISTRY: giftshop90
  DOCKER_REPOSITORY: elites

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      # Matrix strategy to build multiple services in parallel
      matrix:
        service:
          - name: auth
            dockerfile: "Auth Service/Dockerfile"
            context: .
            tag_name: "auth" 
          - name: catalog
            dockerfile: "Catalog Service/Dockerfile"
            context: .
            tag_name: "catalog"
          - name: ordering
            dockerfile: "Ordering Service/Dockerfile"
            context: .
            tag_name: "ordering"
          - name: payment
            dockerfile: "Payment Service/Dockerfile"
            context: .
            tag_name: "payment"
          - name: notification
            dockerfile: "Notification Service/Dockerfile"
            context: .
            tag_name: "notification"
          - name: gateway
            dockerfile: "API Gateway/Dockerfile"
            context: .
            tag_name: "gateway"
          - name: delivery
            dockerfile: "Delivery Service/Dockerfile"
            context: .
            tag_name: "delivery"

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ${{ matrix.service.context }}
          file: ${{ matrix.service.dockerfile }}
          push: true
          tags: |
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ matrix.service.tag_name }}-latest
            ${{ env.DOCKER_REGISTRY }}/${{ env.DOCKER_REPOSITORY }}:${{ matrix.service.tag_name }}-${{ github.sha }}
          cache-from: type=gha
          cache-to: type=gha,mode=max